services:
  database:
    container_name: on-boarding-java
    image: mariadb:11.4
    restart: no
    ports:
      - "53306:3306"
    environment:
      MARIADB_USER: wedatalab
      MARIADB_PASSWORD: wedatalab
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: on-boarding-java
