spring:
  datasource:
    url: jdbc:mysql://localhost:${LOCAL_MYSQL_PORT}/test?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_MYSQL_USER}
    password: ${LOCAL_MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true